### PR TITLE
Fixed root path to line up with router-generator

### PR DESCRIPTION
**Pull request by carl-sauter**
Fixes issue #1240

### CODE REVIEW

**Comment by schiller-manuel** [comment]
I am not sure `process.cwd()` is a good idea. What happens if vite is started from another directory?
I think (but I probably not understand the problem fully) there must be another solution that does not rely on `cwd`.

**Comment by Kinqdos** [comment]
Yeah I see your point. Its the same behavior as the router cli. It searches for routes (and the config file) from the directory you started the cli / vite. This is already the behavior of the route generator. The problem is that the plugin wich handles the hmr updates always takes the vite root directory as "starting" point. (vite root is the directory with the index.html) 
Another solution would be passing the vite root to the route generator instead of passing a relative directory.

**Comment by schiller-manuel** [comment]
"edit the router generator " in which way?

**Comment by Kinqdos** [comment]
Because the generator function exported by the router-generator only takes the userConfig as argument. So you have to add the root directory as argument

**Comment by schiller-manuel** [comment]
i see no problem with this additional change, can you update the PR?

**Comment by Kinqdos** [comment]
Yes I can do! My concern is, that other packages wich also depend on the `generator`function, will break with the changes to the arguments.
P.S: The `getConfig` function from the router-generator also relies on cwd as fallback:
```typescript
export async function getConfig(
  inlineConfig: Partial<Config> = {},
  configDirectory?: string,
): Promise<Config> {
  if (configDirectory === undefined) {
    configDirectory = process.cwd()
  }
...
```

**Comment by Kinqdos** [comment]
Any thoughts? Or should I start update the pr?

**Comment by schiller-manuel** [comment]
can't you add the root directory as optional argument, if it is not set, fall back to `cwd`?

**Comment by Kinqdos** [comment]
Just thinking why to change the behavior here? The router-generator relies on cwd why can't the vite plugin? With this changes we are introducing a different behavior between the vite plugin and the cli. The vite plugin is looking for config in the vite route directory, but if you switch over to using the cli nothing will work. The cli is looking for the config in the cwd and not in the vite root. So you have to move your config from the vite root to the cwd and update the paths in the config.

Is this a better solution than keeping the cwd solution in the vite-plugin?

**Comment by schiller-manuel** [comment]
ok, let's merge this, and wait for complaints :)

**Pull request merged**
